version: '3.8'

services:
  php-web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-web
    volumes:
      - ./php/index.php:/var/www/html/index.php
      - ./php/db.php:/var/www/html/db.php
    expose:
      - "9000" # Експонуємо порт 9000 для PHP-FPM

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/:/var/www/html
      - ./certs/:/etc/nginx/certs/
    ports:
      - "8080:80" # HTTP
      - "443:443"  # HTTPS
      - "2053:2053" # HTTPS для phpMyAdmin
      - "2055:2055" # HTTPS для React
    depends_on:
      - php-web

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: my_database
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
    expose:
      - "80" # phpMyAdmin буде доступний через nginx на порту 2050
    depends_on:
      - db

  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000"
    volumes:
      - ./react-app/app:/app
    depends_on:
      - nginx